- name: remove leftovers
  file:
    path: "{{ item }}"
    state: absent
    recurse: no
  with_items:
    - "/opt/openstack-ansible"
    - "/etc/openstack_deploy"
- name: clone osa repository
  git:
    repo: "https://review.openstack.org/p/openstack/openstack-ansible.git"
    dest: "/opt/openstack-ansible"
    version: "master"
- name: copy openstack_deploy
  shell: "/bin/cp -rf /opt/openstack-ansible/etc/openstack_deploy /etc/openstack_deploy"
- name: copy osa configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/openstack_deploy"
  with_items:
    - "files/openstack_user_config.yml"
    - "files/user_variables.yml"
- name: copy cinder configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/openstack_deploy/env.d"
  with_items:
    - "files/cinder.yml"
    - "files/cinder-volume.yml"
- name: change the haproxy state from disable to enable
  replace:
    dest: "/opt/openstack-ansible/playbooks/os-keystone-install.yml"
    regexp: '(\s+)haproxy_state: disabled'
    replace: '\1haproxy_state: enabled'
- name: copy OPNFV OpenStack playbook
  copy:
    src: "files/setup-openstack.yml"
    dest: "/opt/openstack-ansible/playbooks"
- name: bootstrap ansible on opnfv host
  command: "/bin/bash ./scripts/bootstrap-ansible.sh"
  args:
    chdir: "/opt/openstack-ansible"
- name: generate password token
  command: "python pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml"
  args:
    chdir: "/opt/openstack-ansible/scripts"
