---
- name: remove existing bifrost inventory file
  file:
    path: /tmp/bifrost-inventory.yml
    state: absent
- name: create bifrost inventory file
  template:
    src: "../templates/bifrost-inventory.yml.j2"
    dest: "/tmp/bifrost-inventory.yml"
