---
- name: remove existing bifrost inventory file
  file:
    path: "{{ bifrost_inventory_file }}"
    state: absent
- name: create bifrost inventory file
  template:
    src: "templates/bifrost-inventory.yml.j2"
    dest: "{{ bifrost_inventory_file }}"
