---
- include_vars: "libvirt-nodes-{{ xci_flavor }}.yml"
  connection: local
- name: create directory to store qcow2 images
  file:
    path: /var/lib/libvirt/images
    state: directory
    mode: 0755
  become: true
- name: destroy vms
  virt:
    name: "{{ item.key }}"
    command: destroy
  with_dict: "{{ nodes }}"
  ignore_errors: True
- name: undefine vms
  virt:
    name: "{{ item.key }}"
    command: undefine
  with_dict: "{{ nodes }}"
  ignore_errors: True
- name: remove qcow2 image for vms
  file:
    path: "/var/lib/libvirt/images/{{ item.key }}.qcow2"
    state: absent
  with_dict: "{{ nodes }}"
  become: true
- name: create qcow2 image for vms
  shell: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item.key }}.qcow2 {{ item.value.disk_size }}G"
  with_dict: "{{ nodes }}"
  become: true
- name: define vm
  virt:
    name: "{{ item.key }}"
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
  with_dict: "{{ nodes }}"
