---
- hosts: localhost
  connection: local
  vars_files:
    - ../var/opnfv.yml
    - ../var/node.yml
    - ../var/network.yml
  roles:
    - create-virtual-environment
    - install-bifrost
    - create-bifrost-inventory
