---
- name: create directory to store qcow2 images
  file:
    path: /var/lib/libvirt/images
    state: directory
    mode: 0755
- name: destroy vm
  virt:
    name: "{{ item.key }}"
    command: destroy
  with_dict: "{{ nodes }}"
  ignore_errors: True
- name: undefine vm
  virt:
    name: "{{ item.key }}"
    command: undefine
  with_dict: "{{ nodes }}"
  ignore_errors: True
- name: remove qcow2 image for vm
  file:
    path: "/var/lib/libvirt/images/{{ item.key }}.qcow2"
    state: absent
  with_dict: "{{ nodes }}"
- name: create qcow2 image for vm
  shell: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item.key }}.qcow2 {{ item.value.disk_size }}"
  with_dict: "{{ nodes }}"
- name: define vm
  virt:
    name: "{{ item.key }}"
    command: define
    xml: "{{ lookup('template', '../templates/vm.xml.j2') }}"
  with_dict: "{{ nodes }}"
